export const INSERT_DATA_REQUEST = 'INSERT_DATA_REQUEST'
export const INSERT_DATA_SUCCESS = 'INSERT_DATA_SUCCESS'
export const INSERT_DATA_FAILURE = 'INSERT_DATA_FAILURE'


export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

export const GET_USER_DATA = 'GET_USER_DATA'

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE'